#This file is to write a pipeline
#This file is for cloud build
steps:
# This step builds the container image.
  - name: "gcr.io/cloud-builders/docker" # gcr google cloud container registery
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stedi-liya:latest"
      #gcr is a famous docker registry 
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args: 
      - "push"
      - "gcr.io/$PROJECT_ID/stedi-liya:latest"
  - name: "gcr.io/cloud-builders/docker"
    id: Run
    args: 
      - "run"
      - "gcr.io/$PROJECT_ID/stedi-liya:latest"
#This step deploys the dev application in Kubenetes      
  - name: gcr.io/cloud-builders/gke-deploy
      id: Deploy
      args:
      - run
      - --filename=manifest.yaml
      - --image=gcr.io/$PROJECT_ID/stedi-liya:latest
      - --location=us-west1-b
      - --output=/tmp/outputdev
      - --cluster=cluster-2
      