apiVersion: apps/v1
kind: Deployment
metadata: 
  name: liya-stedi
spec:
  replicas: 1
  selector: 
    matchLabels:
        app: liya-stedi
  template:
    metadata:
      labels:
        app: liya-stedi
    spec:
      containers:
        - name: sean-stedi
          image: gcr.io/power-glove/stedi-liya:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3










