#This file is for kubenete # Using Pipeline taking more time so we are using Kubenete
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: liya-stedi
spec:
  replicas: 1
  selector: 
    matchLabels:
        app: liya-stedi
  template:
    metadata:
      labels:
        app: liya-stedi
    spec:
      containers:
        - name: liya-stedi
          image: gcr.io/power-glove/stedi-liya:latest
          command: ["npm"]
          args: ["run","start"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".4"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
--- # This three - seperates two documents in a yaml file.
# Adding load balancers handles the web or user traffic to the Kubenete deployment.
apiVersion: v1
kind: Service
metadata:
  name: liya-stedi-loadbalancer
spec:
  selector:
    app: liya-stedi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000









