#This file is for kubenete # Using Pipeline taking more time so we are using Kubenete
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: liya-stedi
spec:
  replicas: 1
  selector: 
    matchLabels:
        app: liya-stedi
  template:
    metadata:
      labels:
        app: liya-stedi
    spec:
      containers:
        - name: sean-stedi
          image: gcr.io/power-glove/stedi-liya:latest
          ports:
            - containerPort: 4567
          resources:
            limits:
              cpu: ".125"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3










